name: Iris
gender: female
tank_id: tank-14-iris
wikipedia_url: http://kiwix-simple:8080
wikipedia_variant: simple-english
ollama_url: http://ollama:11434
ollama_model: llama3.2:latest
prompt_version: v8.0
extensions:
  - visual
log_dir: /logs/tank-14-iris
exploration:
  think_time_min: 5
  think_time_max: 15
